name: Continuous Integration

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.1
          no-cache: false

      - name: Install
        run: |
          bun install --frozen-lockfile --production --ignore-scripts

      - name: Build
        run: |
          bun run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install --frozen-lockfile --ignore-scripts

      - name: Lint and Format
        run: |
          bun run lint
          bun run format

      - name: Test
        run: |
          bun test
